### ISSUE TITLE
No fall damage

### ISSUE THREAD

**Issue by nomisum** [gruppe-adler/GRAD-Undead#1]
Bug report from the community:

"you can fall any height without taking any shock damage. Is there anyway you can make it so we go unconscious from certain heights?"

**Comment by y0014984** [comment]
I've tested that. If you jump from great height you deal damage with type 1 which is EDamageType.COLLISION

This damage type does not apply to hitzones directly but to the 'Health' HitZone, which is kind of an overall health indicator. If your health on the 'Health' HitZone drops to 0 you die. It has a value of 100. So if the fall damage is 100 or higher you die immediately. There seems to be no value where you get unconscious before that. Also, there are probably no other drawbacks of the fall damage. You get a visual indicator of the shock but that's it. 

So, the damage is still there but you won't die. We could add unconsciousness if the fall damage is above a certain threshold. I will try that. Excluding this type of damage as @nomisum suggested would lead to player's death. That's not what we want.

**Comment by nomisum** [comment]
how about breaking players legs if damage exceeds threshold, too?

makes no sense to me to have everything allocated to a global health instead of limbs.

**Comment by y0014984** [comment]
Yes, I had the same idea and already implemented that. Now it works as follows:

- Fall damage (exactly collision damage) is always applied to the legs (6 different parts of the legs but mainly the limbs)
- If the amount of fall damage is above 25 (this is a fall from roughly 8-10 meters) the player gets unconscious
- the player will automatically wake up after 15 sec. (This is necessary because unconsciousness is only ment to be created by blood loss which we don't have; So the player would never wake up again)
- Fall from great height leads to impaired movement and injured legs.
- Player can handle the damage by itself in the inventory (it's not bleeding, so only morphine is usefull to speed up healing)

<img width="268" alt="Screenshot 2023-10-05 093634" src="https://github.com/gruppe-adler/GRAD-Undead/assets/50139270/d81a6c0a-1fad-4d6c-b3f5-78edec5b111f">

Now we should test that. @nomisum

**Comment by y0014984** [comment]
I updated the version in the Reforger Workshop: https://reforger.armaplatform.com/workshop/5E68F6FA97DAB5CD-GRADUndead

Now we can test it.
